# Generated by Django 3.0.7 on 2020-10-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieCalification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
