# Generated by Django 3.0.7 on 2020-10-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieCalification', '0002_pelicula_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(),
        ),
    ]
