# Generated by Django 3.0.7 on 2020-10-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieCalification', '0003_auto_20201019_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
